apiVersion: v1
kind: Service
metadata:
  name: inference-service
  labels:
    app: inference-service
spec:
  type: ClusterIP
  selector:
    app: inference-service
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
